title: Runtaskic
description: Fantas(k)tic command-line for execution of regular long sequential or parallel tasks.
url: https://joxit.dev/runtasktic
google_analytics: G-T158HYBVZ2
remote_theme: joxit/joxit.github.io
author: Jones Magloire
twitter:
  username: Joxit
instagram:
  username: jox.it
